spring:
  server:
    port: 8081
  datasource:
    url: jdbc:postgresql://localhost:4003/history
    username: postgres
    password: password
  devtools:
    restart:
      poll-interval: 2s
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 4006

